### ISSUE TITLE
Network error on publish

### ISSUE THREAD

**Issue by Nv7-GitHub** [canonical/action-publish#20]
It builds successfully and gets to the publish stage, in which it uploads 100% but then disconnects due to a network error:
```
Pushing 'graphwhiz_0+git.d4e3a53_amd64.snap' [===========================] 100%
There seems to be a network error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
/snap/bin/snapcraft logout
Credentials cleared.
```
And then it fails. Any idea on why this is happening and how to fix this?

**Comment by jhenstridge** [comment]
Did this happen just once, or is it reproducible? If it is just a one off networking glitch, there might not be anything I can do about it from the action end.

**Comment by Nv7-GitHub** [comment]
It was a one time thing, so I'm just guessing it was an issue on github's end
