### ISSUE TITLE
Unable to publish: macaroon auth error

### ISSUE THREAD

**Issue by ankurk91** [canonical/action-publish#23]
Hi,

It was working fine around 20 days ago, but broken today, see screenshot
![Screenshot from 2022-02-02 12-30-29](https://user-images.githubusercontent.com/6111524/152108716-3385f49d-10e5-4968-9ec4-92283dd67fdd.png)

**Another related issue:**
When i tried to run this command to generate new secrets, got error too.

```
snapcraft --version                          
snapcraft, version 6.0.2

snapcraft export-login --snaps=PACKAGE_NAME \
      --acls package_access,package_push,package_update,package_release \
      exported.txt
Enter your Ubuntu One e-mail address and password.
If you do not have an Ubuntu One account, you can create one at https://snapcraft.io/account
Email: my_valid_email_here
Password: 
Store Error: Failed to get macaroon
```

I did not change anything in secrets.

Any help?

**Comment by jhenstridge** [comment]
My usual thought would be that the macaroon you had stored as a secret had expired, in which case doing `snapcraft export-login` and updating the secret would be the right option. But I see you've tried that already.

It looks like this could be a problem on the server side. I suspect it is likely to be temporary, and will resolve itself if you try again in a few hours. I don't see any obvious notes announcements about upgrades or downtime though, which is a bit surprising.

**Comment by ankurk91** [comment]
Okay, lets wait for server/api to get fixed.

**Comment by ankurk91** [comment]
It has been resolved
